name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medico
      POSTGRES_PORT: 5432
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker stack
      run: docker-compose up -d

    - name: Check running containers
      run: docker ps
